# Generated by Django 3.2.4 on 2021-06-08 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_view_all_borrowed_books', 'one can view all borrowed books'),)},
        ),
    ]
